# Generated by Django 4.1b1 on 2022-07-13 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AbstractItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "abstractitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reports.abstractitem",
                    ),
                ),
            ],
            bases=("reports.abstractitem",),
        ),
        migrations.CreateModel(
            name="DepartmentType",
            fields=[
                (
                    "abstractitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reports.abstractitem",
                    ),
                ),
            ],
            bases=("reports.abstractitem",),
        ),
        migrations.CreateModel(
            name="ProcessType",
            fields=[
                (
                    "abstractitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reports.abstractitem",
                    ),
                ),
            ],
            bases=("reports.abstractitem",),
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(blank=True, null=True, verbose_name="업데이트 날짜"),
                ),
                ("operation", models.CharField(max_length=70, verbose_name="작업내용")),
                ("effective_date", models.DateField(verbose_name="실시 일자")),
                (
                    "prev_image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="notice",
                        verbose_name="개선 전 이미지",
                    ),
                ),
                ("prev_risk", models.TextField(null=True, verbose_name="개선 전 유해인자")),
                (
                    "prev_frequency",
                    models.IntegerField(blank=True, null=True, verbose_name="개선 전 빈도"),
                ),
                (
                    "prev_importance",
                    models.IntegerField(blank=True, null=True, verbose_name="개선 전 중요도"),
                ),
                (
                    "after_image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="notice",
                        verbose_name="개선 후 이미지",
                    ),
                ),
                ("after_risk", models.TextField(null=True, verbose_name="개선 대책")),
                (
                    "after_frequency",
                    models.IntegerField(blank=True, null=True, verbose_name="개선 후 빈도"),
                ),
                (
                    "after_importance",
                    models.IntegerField(blank=True, null=True, verbose_name="개선 후 중요도"),
                ),
                (
                    "improvement_date",
                    models.DateField(blank=True, null=True, verbose_name="개선 예정일"),
                ),
                (
                    "improvement_officer",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="개선 책임자"
                    ),
                ),
                (
                    "is_completion",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="완료여부"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.company",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department",
                        to="reports.departmenttype",
                        verbose_name="부서명",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.processtype",
                        verbose_name="공정명",
                    ),
                ),
            ],
        ),
    ]
