# Generated by Django 4.0.2 on 2022-07-11 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateField(verbose_name='업데이트 날짜')),
                ('operation', models.CharField(max_length=70, verbose_name='작업내용')),
                ('effective_date', models.DateField(verbose_name='실시 일자')),
                ('prev_image', models.FileField(blank=True, null=True, upload_to='notice', verbose_name='개선 전 이미지')),
                ('prev_risk', models.TextField(null=True, verbose_name='개선 전 유해인자')),
                ('prev_frequency', models.IntegerField(blank=True, null=True, verbose_name='개선 전 빈도')),
                ('prev_importance', models.IntegerField(blank=True, null=True, verbose_name='개선 전 중요도')),
                ('prev_dangerous', models.IntegerField(blank=True, null=True, verbose_name='개선 전 위험성')),
                ('after_image', models.FileField(blank=True, null=True, upload_to='notice', verbose_name='개선 후 이미지')),
                ('after_risk', models.TextField(null=True, verbose_name='개선 전 유해인자')),
                ('after_frequency', models.IntegerField(blank=True, null=True, verbose_name='개선 후 빈도')),
                ('after_importance', models.IntegerField(blank=True, null=True, verbose_name='개선 후 중요도')),
                ('after_dangerous', models.IntegerField(blank=True, null=True, verbose_name='개선 후 위험성')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.company', verbose_name='회사')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.departmenttype', verbose_name='부서명')),
                ('process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.processtype', verbose_name='공정명')),
            ],
        ),
    ]
