# Generated by Django 4.1b1 on 2022-07-22 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AfterPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="선택가능한 옵션")),
            ],
            options={
                "verbose_name_plural": "위험성 감소 대책 및 관리 방안",
            },
        ),
        migrations.CreateModel(
            name="CompanyName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="선택가능한 옵션")),
            ],
            options={
                "verbose_name": "사업장명",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="선택가능한 옵션")),
            ],
            options={
                "verbose_name": "부서",
            },
        ),
        migrations.CreateModel(
            name="Factor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="선택가능한 옵션")),
            ],
            options={
                "verbose_name_plural": "유해위험요인",
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="선택가능한 옵션")),
            ],
            options={
                "verbose_name_plural": "장소",
            },
        ),
        migrations.CreateModel(
            name="Process",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="선택가능한 옵션")),
            ],
            options={
                "verbose_name_plural": "공정명",
            },
        ),
        migrations.CreateModel(
            name="Rater",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="선택가능한 옵션")),
            ],
            options={
                "verbose_name_plural": "평가자",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("effective_date", models.DateField(verbose_name="평가 일시")),
                (
                    "company_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="company_name",
                        to="reports.companyname",
                        verbose_name="사업장명",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="department",
                        to="reports.department",
                        verbose_name="부서명",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="place",
                        to="reports.place",
                        verbose_name="작업명 또는 장소",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="process",
                        to="reports.process",
                        verbose_name="공정명",
                    ),
                ),
                (
                    "rater",
                    models.ManyToManyField(
                        blank=True,
                        related_name="rater",
                        to="reports.rater",
                        verbose_name="평가자",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "리포트",
            },
        ),
        migrations.CreateModel(
            name="RiskType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="선택가능한 옵션")),
            ],
            options={
                "verbose_name_plural": "위험 분류",
            },
        ),
        migrations.CreateModel(
            name="ReportContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("factor_source", models.TextField(verbose_name="유해위험요인 원인")),
                ("row_basis", models.TextField(verbose_name="관련 근거")),
                ("present_measures", models.TextField(verbose_name="현재의 안전보건 조치")),
                ("present_frequency", models.IntegerField(verbose_name="현재 위험성 가능성")),
                ("present_importance", models.IntegerField(verbose_name="현재 위험성 중대성")),
                ("after_frequency", models.IntegerField(verbose_name="개선 후 위험성 가능성")),
                ("after_importance", models.IntegerField(verbose_name="개선 후 위험성 중대성")),
                ("improvement_date", models.DateField(verbose_name="개선 예정일")),
                (
                    "improvement_officer",
                    models.CharField(max_length=20, verbose_name="개선 책임자"),
                ),
                (
                    "present_img",
                    models.ImageField(
                        blank=True, upload_to="report_photos", verbose_name="개선 전 사진"
                    ),
                ),
                (
                    "after_img",
                    models.ImageField(
                        blank=True, upload_to="report_photos", verbose_name="개선 후 사진"
                    ),
                ),
                (
                    "after_plan",
                    models.ManyToManyField(
                        blank=True,
                        related_name="after_plan",
                        to="reports.afterplan",
                        verbose_name="위험성 감소 대책 및 관리 방안",
                    ),
                ),
                (
                    "factor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="factor",
                        to="reports.factor",
                        verbose_name="유해위험요인",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_content",
                        to="reports.report",
                        verbose_name="리포트",
                    ),
                ),
                (
                    "risk_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_type",
                        to="reports.risktype",
                        verbose_name="위험분류",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "리포트 리스트",
            },
        ),
    ]
