# Generated by Django 4.1b1 on 2022-07-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={"verbose_name_plural": "리포트"},
        ),
        migrations.AddField(
            model_name="report",
            name="last_update",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
